server:
  port: 2222

spring:
  application:
    name: gateway
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      
zuul:
  ignoredServices: '*'
  host:
#路由转发至url，超时时间取这两个配置参数
    socket-timeout-millis: 10000
    connect-timeout-millis: 10000
  routes:
    service-ribbon:
      path: /ribbon/**
      serviceId: service-ribbon
#      url: http://127.0.0.1:8081/
      strip-prefix: true
    service-feign:
      path: /feign/**
      serviceId: service-feign
#      url: http://127.0.0.1:8082/
      strip-prefix: false
  max:
    host:
      connections: 5000
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
  enabled: false

#路由转发至serviceId,超时时间用的以下配置
ribbon:
  ReadTimeout: 10000
#  SocketTimeout: 10000
  ConnectTimeout: 3000
  
logging:
  level:
    com.netflix: DEBUG
  